# NOTE: This action will not complete due to needing an SSH key in the "Git Push" step.
# Test this workflow once the repo is moved to GitHub enterprise.
on:
  watch:
    types: [started]
# TODO: add trigger for on-push once this is working.

jobs:
  run-make:
    runs-on: ubuntu-latest
    name: Make Registry Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make Registry
        run: |
          pip3 install -U pip setuptools
          make -C scripts/mkdocs pip_install
          make docs_registry
      - name: Git Push
        run: |
          git config --global user.email "${GIT_EMAIL:-SYSTEM@users.noreply.github.com}"
          git config --global user.name "${GIT_NAME:-SYSTEM}"
          git add docs
          git commit -m "Auto commit: $(date)"
          git push
      - name: Failure Notification
        if: failure()
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "GitHub Action FAILED",
            "body": "This is an automated issue. See repo actions for details."
            }'
